### ISSUE TITLE
Does extra field change results?

### ISSUE THREAD

**Issue by syntagmatic** [stamen/ecoengine#101]
I've been using [parallel coordinates](http://bl.ocks.org/syntagmatic/42d5b54c5cfe002e7dd8) to look at the population of various fields in the database.

But I noticed something strange. When I enable different `extra` fields, I get different sets of observations back. Perhaps observations with values undefined for those fields are excluded from the returned results?

**Comment by danrademacher** [comment]
given commits from @shoeswat saying he fixed this, I'm closing it out
