### ISSUE TITLE
Add method to help user get queries from Explore to Compare

### ISSUE THREAD

**Issue by danrademacher** [stamen/ecoengine#114]
This is going to be some slightly fancied-up version of cut and paste, but the idea is to make it as obvious as we can without pulling in lots of hard stuff about sessions and storing things in cookies, etc.

**Comment by danrademacher** [comment]
At this point, we just need a button on the Explore view that pops up a dialogue with the geojson link, like the share button on Compare view, but with unshortened link and different copy:
* "Get query for Compare View"
* Inside the box, include a button, "Open Compare View" that opens compare in new tab

**Comment by standardpixel** [comment]
![screenshot 2015-02-26 13 07 53](https://cloud.githubusercontent.com/assets/15744/6401895/87ddf462-bdb8-11e4-92cf-981bd2b4a806.png)
