### ISSUE TITLE
Decades Facet

### ISSUE THREAD

**Issue by syntagmatic** [stamen/ecoengine#120]
A `decades` facet in the Search api would let the [Oaks](http://studio.stamen.com/berkeley/show/prototypes/covis/oaks.html#q=quercus&split=scientific_name) prototype create [Woodrats over Decades](http://studio.stamen.com/berkeley/show/prototypes/covis/multiples-decades.html)

**Comment by postfalk** [comment]
@syntagmatic I implemented decade facets. They might not be fully indexed, the process is currently running. They start at 1841-1850. For this reason you need to increase the facets_limit to maybe 20.

e.g.

https://dev-ecoengine.berkeley.edu/api/search/?facets_limit=20

This return becomes somewhat heavy, so I might add field selection to this view down the road.

**Comment by syntagmatic** [comment]
Thanks Falk, I set a limit of 24

http://stamen.github.io/ecoengine/prototypes/covis/oaks.html#q=neotoma&split=decade
