### ISSUE TITLE
Environment layers returning 500

### ISSUE THREAD

**Issue by syntagmatic** [stamen/ecoengine#122]
Failed to load resource: https://dev-ecoengine.berkeley.edu/api/tiles/tasmax_rcp60_r1i1p1_gfdl-esm2m-2031-02-16/2/2/0/ the server responded with a status of 500 (INTERNAL SERVER ERROR)

**Comment by postfalk** [comment]
Ah, forgot to copy these files over on redeploy. Could you please try again
and see whether it works no. If so, please close. Thx

On Thu, Feb 19, 2015 at 2:47 PM, Kai <notifications@github.com> wrote:

> Assigned #122 <https://github.com/stamen/ecoengine/issues/122> to
> @postfalk <https://github.com/postfalk>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/122#event-238766195>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by syntagmatic** [comment]
It doesn't work but let me take another look at this tomorrow, there was an old issue with raster layers where I needed to store tile URLs in a static json file. Those may be out-of-date now.

**Comment by syntagmatic** [comment]
Never mind, it does work!

**Comment by postfalk** [comment]
Just successfully requested this one

https://dev-ecoengine.berkeley.edu/api/tiles/tasmax_rcp60_r1i1p1_gfdl-esm2m-2031-02-16/1/0/0/

Falk

On Thu, Feb 19, 2015 at 3:15 PM, Kai <notifications@github.com> wrote:

> It doesn't work but let me take another look at this tomorrow, there was
> an old issue with raster layers where I needed to store tile URLs in a
> static json file. Those may be out-of-date now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/122#issuecomment-75159595>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
