### ISSUE TITLE
API returning 0 results with 'q' parameter

### ISSUE THREAD

**Issue by syntagmatic** [stamen/ecoengine#125]
Example link: https://dev-ecoengine.berkeley.edu/api/observations/?q=%22%22&page_size=100

Possibly re-indexing?

**Comment by postfalk** [comment]
I think the SearchEngine treats q= differently from q="". The first case
meaning that there is no filter applied, the second looking for tokens with
an empty string. However, I will investigate this issue further, maybe
adjusting settings will help.

Falk

On Mon, Feb 23, 2015 at 1:59 PM, Kai <notifications@github.com> wrote:

> Assigned #125 <https://github.com/stamen/ecoengine/issues/125> to
> @postfalk <https://github.com/postfalk>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/125#event-240499829>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by syntagmatic** [comment]
`q=` is also showing 0 results: https://dev-ecoengine.berkeley.edu/api/observations/?q=&page_size=100

`start_date` works though, so it's probably a Search API issue https://dev-ecoengine.berkeley.edu/api/observations/?start_date=1990&page_size=100

**Comment by postfalk** [comment]
Returns nothing

https://dev-ecoengine.berkeley.edu/api/observations/?q=%22%22&page_size=100

Works as exspected

https://dev-ecoengine.berkeley.edu/api/observations/?q=&page_size=100

for me.



On Mon, Feb 23, 2015 at 2:14 PM, Kai <notifications@github.com> wrote:

> q= is also showing 0 results:
> https://dev-ecoengine.berkeley.edu/api/observations/?q=&page_size=100
>
> start_date works though, so it's probably a Search API issue
> https://dev-ecoengine.berkeley.edu/api/observations/?start_date=1990&page_size=100
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/125#issuecomment-75648874>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by syntagmatic** [comment]
Our prototypes are working again too now.

**Comment by postfalk** [comment]
Yeah, maybe the SearchEngine service was down. Will put it under supervisor
and make sure that it runs all the time.
Falk

On Mon, Feb 23, 2015 at 2:27 PM, Kai <notifications@github.com> wrote:

> Our prototypes are working again too now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/125#issuecomment-75651205>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
