### ISSUE TITLE
Quicker integration

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#129]
Is there a chance to add a /dist folder to the repo and have a single div on which I could attach the app to? Than I could just create a template like this

```html

<body>
    <!-- CMS stuff here -->
    <div id="explorer_goes_here">
    <!-- more CMS stuff here -->
    <script src="static/ecoengine/dist/stamen_explorer.js"></script>
</body>
```

... and collect the code using bower. This way I could rid of my git sub module.

**Comment by postfalk** [comment]
It might be even there already. Can you please give me some directions.
Thanks

**Comment by danrademacher** [comment]
Sorry -- I didn't see this when it got posted! Need to check my notification settings. 

Just checked with @standardpixel: We can make a 'build' branch similar to https://github.com/stamen/ecoengine-compare/tree/build

For div targeting, we can make that happen -- but not till Monday. Is that OK?

**Comment by postfalk** [comment]
This is ok with me. Thx.

On Wed, Mar 4, 2015 at 1:59 PM, Dan Rademacher <notifications@github.com>
wrote:

> Sorry -- I didn't see this when it got posted! Need to check my
> notification settings.
>
> Just checked with @standardpixel <https://github.com/standardpixel>: We
> can make a 'build' branch similar to
> https://github.com/stamen/ecoengine-compare/tree/build
>
> For div targeting, we can make that happen -- but not till Monday. Is that
> OK?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/129#issuecomment-77259078>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by danrademacher** [comment]
This is *almost* done.
* Here's Compare loading in a div: http://studio.stamen.com/berkeley/show/holos/compare/
* And here's Explore _almost_ working: http://studio.stamen.com/berkeley/show/holos/explore/

@standardpixel needs to get that second one working and update the docs -- we made this install method (inserting into a div with javascript) optional on build with Gulp.

**Comment by danrademacher** [comment]
Ok, we've got this set up for both Explore and Compare. @standardpixel has the install steps documented here:
https://github.com/stamen/ecoengine#holos-integration
https://github.com/stamen/ecoengine-compare#holos-integration

@postfalk can you take a look and make sure they are clear to you?

**Comment by danrademacher** [comment]
I'm going to close this one since we've worked through most of the issues and have a couple of other items open.
