### ISSUE TITLE
Compare: slider for Point sizing?

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#130]
The default Point size is awfully small, no matter the zoom level. Perhaps adding a slider bar to control size like for hexabins?

**Comment by standardpixel** [comment]
Very good point. Eric R was mentioning that to me as well. 

Kai and I were were thinking of lifting the size. Adding a slider would make it no different from the hexbins since they are essentially the same. Kai suggested a 2 or 4px radius. I can bump it is to two today and see how we like it.

**Comment by mkoo** [comment]
Bumping up would help, maybe to 4 px. 
Comparing with what 2px looks like as hex, 2 px still tiny.

**Comment by standardpixel** [comment]
I think this works very well
![screenshot 2015-03-02 12 21 31](https://cloud.githubusercontent.com/assets/15744/6449594/d00968ae-c0d6-11e4-9779-d82a63ac5c52.png)
