### ISSUE TITLE
Download all option from Explore?

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#135]
What is the feasibility to have the option of downloading all results as CSV not just the paged dataset from the main page of Explore or even in the Queries page? Do we need an option in the API for that specifically?
(requested feature)

**Comment by danrademacher** [comment]
An API option would be best and most stable way forward here in my opinion. Incrementally downloading them and writing to a file might be possible and could build on the live loading we did for Compare, but it's not easily built in a way that's clear for end users, and the functionality isn't going to be easily added to other EcoEngine tools. It's basically a workaround.

**Comment by mkoo** [comment]
thnking about this more, I agree. let me close and redo this issue for the API. thanks.

**Comment by syntagmatic** [comment]
It's not ideal by any means, but there is the bulk download tool http://stamen.github.io/ecoengine/prototypes/loading/bulk-download.html

**Comment by danrademacher** [comment]
Oh, I totally forgot about that prototype!
