### ISSUE TITLE
HTML Title tag on Compare tool (typo)

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#136]
Sorry for this out of scope issue (not urgent at all): could Compare example page have its title tag fix the typo? (should be Berkeley Ecoengine Compare or just Ecoengine Compare) Thanks!

**Comment by danrademacher** [comment]
OK, fixed in the master branch: https://github.com/stamen/ecoengine-compare/commit/b69e7dd34b9cfc5feec24e1dcb3e53a5d182f53e

@standardpixel, can you make sure this goes live in the build and gh-pages branch? I don't want want to break anything.

**Comment by standardpixel** [comment]
Github pages is updated
