### ISSUE TITLE
Move over to production API on Friday 3/20 or after

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#143]
... or @syntagmatic. The production API is (almost - reindexing in progress) ready to be used by the Stamen apps.

Please post failing requests as issues. Thx Falk

**Comment by danrademacher** [comment]
@postfalk: we can make this change today, but we're not in active testing mode on our end. Are you guys also running Explore and Compare on holos.berkeley.edu? Looks like the holos home page is updated but not https://holos.berkeley.edu/explore.

**Comment by postfalk** [comment]
Well, holos.berkeley.edu is actually updated BUT for some reason the build
of the applications is still failing. I hope to figure this out in the next
few hours.


On Mon, Mar 23, 2015 at 9:48 AM, Dan Rademacher <notifications@github.com>
wrote:

> @postfalk <https://github.com/postfalk>: we can make this change today,
> but we're not in active testing mode on our end. Are you guys also running
> Explore and Compare on holos.berkeley.edu? Looks like the holos home page
> is updated but not https://holos.berkeley.edu/explore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/143#issuecomment-85090760>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by standardpixel** [comment]
Both this and the [EcoEngine Compare](https://github.com/stamen/ecoengine-compare) repos have been updated to use the production API.
