### ISSUE TITLE
Compare still does not initialize properly

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#144]
Sorry, it is me again. The templating seems to work now but the app still does not initialize properly:

1. The layer menu is underneath the map instead on the right side.
2. Map does not load. 

Can you see whether there is something wrong with my htlm (e.g. copy it in your build).

```html
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="./static/css/vendor.css">
        <link rel="stylesheet" type="text/css" href="./static/css/base.css">
   </head>
    <body>
        <div id="ecoengine-compare-container"></div>
        <script src="./static/js/stamen/ecoengine-compare.min.js"></script>
        <script src="./static/js/stamen/holos-init.js"></script>
  </body>
</html>
```

All the files load properly (I had to move the holos-init.js script down to the body. It won't work in the header as described in your directions.

**Comment by standardpixel** [comment]
Is there a JS error in the console?

**Comment by postfalk** [comment]
TypeError: z is null
http://localhost:8002/static/js/stamen/ecoengine-compare.min.js
Line 12

**Comment by postfalk** [comment]
If I use the non-minified version I get

TypeError: rootNode is null
http://localhost:8002/static/js/stamen/ecoengine-compare.js
Line 17629

**Comment by postfalk** [comment]
What does .env.json do?

**Comment by standardpixel** [comment]
It lets you define the root directory of assets. Honestly it is only really useful in the standalone case. The build process still requires it is there

**Comment by postfalk** [comment]
Compare has similar issues, sorry what I am missing?

**Comment by danrademacher** [comment]
@postfalk, can we do a screen share of your screen so we can see the errors you're seeing live? We have an inject working on [our studio server](studio.stamen.com/berkeley/show/holos/compare/), as you know, but we're not really able to test and repro the errors you're seeing.

**Comment by danrademacher** [comment]
https://global.gotomeeting.com/join/918808973

**Comment by danrademacher** [comment]
Or maybe we need an in-person session with you both? I think these issues can get resolved pretty quickly, but at this point, real-time communication would be ideal

**Comment by postfalk** [comment]
I am not sure whether I can do a quick screen share. Let me find out.

On Tue, Mar 24, 2015 at 5:05 PM, Dan Rademacher <notifications@github.com>
wrote:

> @postfalk <https://github.com/postfalk>, can we do a screen share of your
> screen so we can see the errors you're seeing live? We have an inject
> working on our studio server
> <http://studio.stamen.com/berkeley/show/holos/compare/>, as you know, but
> we're not really able to test and repro the errors you're seeing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/144#issuecomment-85745050>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
What is Eric's email address?

**Comment by standardpixel** [comment]
evg@stamen.com

**Comment by postfalk** [comment]
ok


On Tue, Mar 24, 2015 at 5:07 PM, Dan Rademacher <notifications@github.com>
wrote:

> https://global.gotomeeting.com/join/918808973
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/144#issuecomment-85745258>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by danrademacher** [comment]
Eric's joined the BlueJeans meeting. Says you're not in yet.

**Comment by postfalk** [comment]
Did you start the meeting?

On Tue, Mar 24, 2015 at 5:30 PM, Falk Schuetzenmeister <
schuetzenmeister@berkeley.edu> wrote:

> ok
>
>
> On Tue, Mar 24, 2015 at 5:07 PM, Dan Rademacher <notifications@github.com>
> wrote:
>
>> https://global.gotomeeting.com/join/918808973
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/stamen/ecoengine/issues/144#issuecomment-85745258>.
>>
>
>
>
> --
> Falk Schuetzenmeister, PhD
> Web Application Developer
> Geospatial Innovation Facility <http://gif.berkeley.edu/>
>
> University of California Berkeley
> 111 Mulford Hall
> 94720 Berkeley, CA
>
> schuetzenmeister@berkeley.edu
> 1-510-642-4897
>
>


-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by danrademacher** [comment]
It says "the moderator has not joined yet" -- I assume you are the moderator?

**Comment by postfalk** [comment]
Oh I switched over he should wait me.

On Tue, Mar 24, 2015 at 5:34 PM, Dan Rademacher <notifications@github.com>
wrote:

> Eric's joined the BlueJeans meeting. Says you're not in yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/144#issuecomment-85759202>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by mkoo** [comment]
Did this get resolved in today's call? I am not sure if this is related or not, but will file here unless it warrants its own issue: Compare is not loading data properly, repeating the same data for a few points until it times out or maxes out.
Screenshot shows the few points that load then maxes out. Second shows the data from one of the hexbins (just repeats the same for 2400+ rows)-no wonder it maxed out!
![screen shot 2015-03-24 at 11 15 19 pm](https://cloud.githubusercontent.com/assets/2523089/6819353/142b2da8-d27d-11e4-99f3-3aa304cf61d1.png)

![screen shot 2015-03-24 at 11 18 02 pm](https://cloud.githubusercontent.com/assets/2523089/6819358/1b62da26-d27d-11e4-8a35-0d410ab01257.png)

**Comment by mkoo** [comment]
debugger view:
![screen shot 2015-03-24 at 11 28 24 pm](https://cloud.githubusercontent.com/assets/2523089/6819385/85a7e200-d27d-11e4-96d7-4fd2e6b0279a.png)

**Comment by standardpixel** [comment]
@mkoo We are looking into this request issue

@postfalk I have pushed some updates to compare. I have removed the need for special build targets completely. Running `gulp` in the root of the master branch will create files in the `build` sub-directory. This includes a fully hostable index.html. Your code should overwrite the index.html in the root of the build directory and replace it with one which calls the html file in the `templates directory`. I have put a tested example of that file [here](https://github.com/stamen/ecoengine-compare/blob/master/holos/index.html.sample)

Please let me know if you are still running into trouble having the gulp build generate files. I was not able to reproduce the issue but my assumption is that it was caused somehow by the bash dependencies which I had in the holos target. I have removed all of the bash dependencies as part of this simplified build.

Thanks!

**Comment by postfalk** [comment]
Seems to work, let me integrate in my template before I close.

**Comment by postfalk** [comment]
@standardpixel one more question. How are the templates found? Relative to the index.html file or relative to the js. Need to adapt this since my template structure gives me restraints here.

**Comment by standardpixel** [comment]
that is determined in holos-init.js, which right now points directly to `./templates/index.html`

**Comment by postfalk** [comment]
Yeah, I saw this. I might give it a shot to change in a fork.

**Comment by postfalk** [comment]
Would it be a good idea to use gulp/require/text in order to create a variable in holos_init.js that already holds the template?

**Comment by postfalk** [comment]
I think I have a better idea using the Django template system.

**Comment by postfalk** [comment]
The beforementioned workflow actually works well (minus holos-init.js).

**Comment by postfalk** [comment]
Yeah works!
