### ISSUE TITLE
Prototype links broken

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#145]
Sorry it be filing an issue now (really!) but all the links to Prototypes are broken (404).
Thanks

**Comment by syntagmatic** [comment]
Hmm, @standardpixel it looks like `gh-pages` now mirrors the `build` branch. Can it mirror the `master` branch?

**Comment by danrademacher** [comment]
@standardpixel has the prototypes back in the gh branch, but they're still giving 404s.

I see this error in the repo settings area:
![image](https://cloud.githubusercontent.com/assets/1423200/6834722/1d76f4ca-d2f3-11e4-8e6e-31f1ba2e94b9.png)

**Comment by danrademacher** [comment]
And these are now fixed!

http://stamen.github.io/ecoengine/prototypes/covis/lizards-woodrats.html

![image](https://cloud.githubusercontent.com/assets/1423200/6837206/20e86378-d307-11e4-85d1-92a17b0f7afe.png)

**Comment by mkoo** [comment]
Perfect-- just in time for prepping for NPS talk!
MK
