### ISSUE TITLE
The little arrow in the very right corner of compare has error message

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#146]

**Comment by danrademacher** [comment]
Gah, another regression

http://stamen.github.io/ecoengine-compare/#2/37.5/-77.5
![image](https://cloud.githubusercontent.com/assets/1423200/6838803/ae2e30b8-d31c-11e4-81ca-b11737a31a40.png)

![image](https://cloud.githubusercontent.com/assets/1423200/6838824/ea8b50a4-d31c-11e4-9070-e95451826c1a.png)

**Comment by standardpixel** [comment]
@postfalk This slipped past in my documenting. Sorry.

You will need to apply for a [google apps key for the URL shortener api](https://developers.google.com/url-shortener/v1/getting_started). Once you have it, add it to the .env.json file with the key `google-key`. I have updated the docs
