### ISSUE TITLE
Compare: vendor.css not built

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#148]
... after latest changes in Gulpfile

**Comment by standardpixel** [comment]
That is working on my side. We may need to troubleshoot further. Would you mind trying again after running `bower update` in the ecoengine-compare root?

**Comment by postfalk** [comment]
Nope not there. I run it from scratch again, fresh git pull.

On Thu, Mar 26, 2015 at 4:12 PM, Eric Gelinas <notifications@github.com>
wrote:

> That is working on my side. We may need to troubleshoot further. Would you
> mind trying again after running bower update in the ecoengine-compare
> root?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/148#issuecomment-86750278>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by standardpixel** [comment]
Interesting. I just tried from Ubuntu 12.04.5 LTS and it failed to run `bower install` as a post install step of `npm install` with an error complaining that the `bower_components` directory did not exist. It worked for me when I ran `bower install` myself after the `npm install` had completed. This works on MacOS Yosemite. 

While in the code, i found a small CSS error which could potentially break the sass compilation process (depending on the version of sass installed). I fixed it in the master branch so you might want to pull again. This will not affect the vendor.css in any way since that is never passed through the sass compiler.

**Comment by postfalk** [comment]
Thx, we will figure that out next week. We are closed today and I am
working on some of my other tasks. Thanks for being so patient with us.

On Thu, Mar 26, 2015 at 5:17 PM, Eric Gelinas <notifications@github.com>
wrote:

> Interesting. I just tried from Ubuntu 12.04.5 LTS and it failed to run bower
> install as a post install step of npm install with an error complaining
> that the bower_components directory did not exist. It worked for me when
> I ran bower install myself after the npm install had completed. This
> works on MacOS Yosemite.
>
> While in the code, i found a small CSS error which could potentially break
> the sass compilation process (depending on the version of sass installed).
> I fixed it in the master branch so you might want to pull again. This will
> not affect the vendor.css in any way since that is never passed through the
> sass compiler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/148#issuecomment-86767575>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
I am trying to understand what is going on. Sofar I found that

```js
mainBowerComponents("**/*.css")
```

as it is called from the vendor-css gulp task
seems to be empty

```js
mainBowerComponents()
``` 

is not (all the bower_components) seem to be in place.

**Comment by postfalk** [comment]
The problem seems to be that glob filtering does not seem to work work without the exact number of subfolders.

```
mainBowerComponents()
```

Gives me absolute path names like ...

```/falk/home/.src/ecoengine-compare/bower_components/leaflet/dist/leaflet.css```

**Comment by postfalk** [comment]
When I change the filter to RegEx it starts working (see below). Not sure whether I am picking the right files and whether it is intended to work with absolute paths. @standardpixel let me know whether I should push to origin master.

```js
gulp.task("vendor-css", function() {
  // console.log(mainBowerFiles())
  // console.log("Files", mainBowerFiles({filter: new RegExp('.css$', 'i')}));
  gulp
  .src(mainBowerFiles({filter: new RegExp('.css$', 'i')}))
  .pipe(concat("vendor.css"))
  .pipe(gulp.dest(paths.css));
});
```

**Comment by standardpixel** [comment]
The previous way worked on OSX and not on Linux. Go ahead and commit it and I'll test it on OSX. Thanks for finding that.

**Comment by postfalk** [comment]
@standardpixel: There was a little error I build into the Gulpfile at line 97 (some bracket thing). Now it builds correctly from my fork. Please close after successful merge and retest. Thx for your patience.

**Comment by standardpixel** [comment]
Will do. Thanks @postfalk
