### ISSUE TITLE
Explore: Where could I find the template? (pls update README.md)

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#149]
The folder build/explore contains two complete html files.

**Comment by standardpixel** [comment]
Will do. The holos-test.html file can be ignored. It is just there to help re-create the holos environment when testing the embed

**Comment by standardpixel** [comment]
I will update the readme

**Comment by postfalk** [comment]
The index.html file as described in the README.md still contains <body> and <script> tags.

**Comment by danrademacher** [comment]
@postfalk can you clarify your last comment? Were there supposed to be code snippets in there?

**Comment by postfalk** [comment]
There should be some sort of template that get attached to the div element.
Currently the entire html document get attached. I changed/simplified the
strategy a little bit and do not use javascript to include the code but
template includes which works a little bit smoother since the folder
structure can be handled server side.

Maybe I should give this a shoot tomorrow and create a pull request.

Falk

On Tue, Mar 31, 2015 at 11:45 AM, Dan Rademacher <notifications@github.com>
wrote:

> @postfalk <https://github.com/postfalk> can you clarify your last
> comment? Were there supposed to be code snippets in there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/149#issuecomment-88204759>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
I think the major problem is that template location and the static location are relative to each other which cannot easily be reproduced within the django template system. Let me think a little bit more thorough about it but I think a good approach would be to use a template include insteaed of a div attachment. This works for compare now.

**Comment by postfalk** [comment]
Yeah, I explored this issue further. The problem is definitely that holos-init.js pulls additional resources (index.html and rstore.json). Since I have to integrate this whole thing into a Django project I need access to the absolute paths. Could we expose this locations somehow so that I would be able to modify the locations according to my project?

**Comment by standardpixel** [comment]
Sure, are you thinking a JSON file or something?

**Comment by postfalk** [comment]
If we do this we could also radically simplify the directory structure of that build.

**Comment by standardpixel** [comment]
In that case, we could just put everything in the root.

**Comment by postfalk** [comment]
Yeah but it would be still the root of the template and not the root of the static directory once deployed.

Like holos.berkeley.edu/explore instead of holos.berkeley.edu/static/wherever.

But if I could point to this locations in my template that would be very helpful.

**Comment by standardpixel** [comment]
(i might be missing something, since it is past 3pm)

If all of the files are in the build branch in a flat directory structure, than that directory could become holos.berkeley.edu/static/wherever and your templates could just be set up to fetch all js / css assets from that directory.

This is assuming you are making your templates and they are not generalized parts or our code. I would still want to ship the build directory with an HTML file for standalone use

**Comment by postfalk** [comment]
That is correct, BUT

1. holos-init.js fetches a copy of index.html to strip of some tags
(basically to get the children of <body>). This happens from a path inside
the code.
2. Another part of the code fetches rstore.json pretty much the same way.

For this reason these locations cannot be easily changed or set from my
template. All the locations I define explicitly within my template will
work perfectly wherever they are.






On Thu, Apr 2, 2015 at 4:27 PM, Eric Gelinas <notifications@github.com>
wrote:

> (i might be missing something, since it is past 3pm)
>
> If all of the files are in the build branch in a flat directory structure,
> than that directory could become holos.berkeley.edu/static/wherever and
> your templates could just be set up to fetch all js / css assets from that
> directory.
>
> This is assuming you are making your templates and they are not
> generalized parts or our code. I would still want to ship the build
> directory with an HTML file for standalone use
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/149#issuecomment-89076785>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
Btw. we need to switch the Gulpfile to Regex for this project too.

Falk

On Thu, Apr 2, 2015 at 4:32 PM, Falk Schuetzenmeister <
schuetzenmeister@berkeley.edu> wrote:

> That is correct, BUT
>
> 1. holos-init.js fetches a copy of index.html to strip of some tags
> (basically to get the children of <body>). This happens from a path inside
> the code.
> 2. Another part of the code fetches rstore.json pretty much the same way.
>
> For this reason these locations cannot be easily changed or set from my
> template. All the locations I define explicitly within my template will
> work perfectly wherever they are.
>
>
>
>
>
>
> On Thu, Apr 2, 2015 at 4:27 PM, Eric Gelinas <notifications@github.com>
> wrote:
>
>> (i might be missing something, since it is past 3pm)
>>
>> If all of the files are in the build branch in a flat directory
>> structure, than that directory could become
>> holos.berkeley.edu/static/wherever and your templates could just be set
>> up to fetch all js / css assets from that directory.
>>
>> This is assuming you are making your templates and they are not
>> generalized parts or our code. I would still want to ship the build
>> directory with an HTML file for standalone use
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/stamen/ecoengine/issues/149#issuecomment-89076785>.
>>
>
>
>
> --
> Falk Schuetzenmeister, PhD
> Web Application Developer
> Geospatial Innovation Facility <http://gif.berkeley.edu/>
>
> University of California Berkeley
> 111 Mulford Hall
> 94720 Berkeley, CA
>
> schuetzenmeister@berkeley.edu
> 1-510-642-4897
>
>


-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by standardpixel** [comment]
Oh, I see. I thought we were getting rid of holos-init all together and do something more like I am doing in the source https://github.com/stamen/ecoengine-compare/blob/master/templates/index.handlebars but in your templating system.

**Comment by postfalk** [comment]
That would be even better.
Falk

On Thu, Apr 2, 2015 at 4:35 PM, Eric Gelinas <notifications@github.com>
wrote:

> Oh, I see. I thought we were getting rid of holos-init all together and do
> something more like I am doing in the source
> https://github.com/stamen/ecoengine-compare/blob/master/templates/index.handlebars
> but in your templating system.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/149#issuecomment-89078393>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by postfalk** [comment]
Thanks so much. So I am waiting for the following tasks to be finished:

1. Change build process so that mainBowerFiles uses filter based on Regex
(opposed to glob).
2. Simplify project structure.
3. Template that can be easily added with {% include "..." %} according the
Django/ninja2 template system (just the html between <body></body> or
whatever gets attached to the <div id="ecoengine-explore-container> will do.
4. Expose location of rstore.json to the template.




On Thu, Apr 2, 2015 at 4:38 PM, Falk Schuetzenmeister <
schuetzenmeister@berkeley.edu> wrote:

> That would be even better.
> Falk
>
> On Thu, Apr 2, 2015 at 4:35 PM, Eric Gelinas <notifications@github.com>
> wrote:
>
>> Oh, I see. I thought we were getting rid of holos-init all together and
>> do something more like I am doing in the source
>> https://github.com/stamen/ecoengine-compare/blob/master/templates/index.handlebars
>> but in your templating system.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/stamen/ecoengine/issues/149#issuecomment-89078393>.
>>
>
>
>
> --
> Falk Schuetzenmeister, PhD
> Web Application Developer
> Geospatial Innovation Facility <http://gif.berkeley.edu/>
>
> University of California Berkeley
> 111 Mulford Hall
> 94720 Berkeley, CA
>
> schuetzenmeister@berkeley.edu
> 1-510-642-4897
>
>


-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by standardpixel** [comment]
I will aim to resolve these today.

**Comment by postfalk** [comment]
Thx

On Fri, Apr 3, 2015 at 10:19 AM, Eric Gelinas <notifications@github.com>
wrote:

> I will aim to resolve these today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/149#issuecomment-89366022>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897

**Comment by standardpixel** [comment]
Okay! We are all set. ecoengine and ecoengine compare have identical build directories now. Both also have an index.ninja2.html file which is basically just an html file with no header or footer. In ecoengine rstore.json is configured in the template near the top.
