### ISSUE TITLE
Not sure whether Google API key actually gets posted

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#153]
I looked at the working compare example (in which the Url shortening does not work). Looking at the request the API key does not seem to be posted. Can you make the example work with the API key so that I know what to expect. 

Thank you very much

**Comment by standardpixel** [comment]
There were two problems actually. You were right @postfalk, the key had been copied over at some point and was not being passed with the request. I fixed that in my last commit. Also, I did not have `studio.stamen.com` as an approved domain in the api console for this key. The example is updated:

`http://studio.stamen.com/berkeley/show/compare/#2/37.5/-77.5`

**Comment by postfalk** [comment]
Thank you

On Mon, Apr 13, 2015 at 4:20 PM, Eric Gelinas <notifications@github.com>
wrote:

> Closed #153 <https://github.com/stamen/ecoengine/issues/153>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/153#event-280290291>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
