### ISSUE TITLE
Explore Tool's 'Get query for Compare' link needs to be updated 

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#154]
The link that Get Query for Compare supplies is this:
https://ecoengine.berkeley.edu/api/observations/?format=geojson&selected_facets=state_province_exact%3A%22Wyoming%22&q=&page_size=1000
which is for copy/pasting in the Add field of Compare, but URL redirects to http://studio.stamen.com/berkeley/show/compare/ (dev instance of Compare tool so not stable). Should open Compare tool on https://holos.berkeley.edu/compare/

Originally posted on [Holos site] (https://github.com/berkeley-gif/holos/issues/71#issuecomment-93851948) until Yoshi pointed out:
@postfalk I need to be able to push to the stamen repo to change this too. The link here is hard coded. See ecoengine.js (after its compiled) on line 23322. 

Can the URL redirect from Explore tool to Compare tool be relative? or other means?

**Comment by danrademacher** [comment]
This is an easy fix -- @standardpixel will push a fix first thing Monday

**Comment by danrademacher** [comment]
@standardpixel pushed a fix for this earlier today: https://github.com/stamen/ecoengine/commit/821f0d5bdda40ca8b008dbc9eeaa3d1874c31273

**Comment by danrademacher** [comment]
Now it's configurable
