### ISSUE TITLE
Confirm that you can add issues

### ISSUE THREAD

**Issue by danrademacher** [stamen/ecoengine#157]
Saw your email and as far as I can see you can add issues here. You're on the same team as mkoo. Can you confirm?

**Comment by shoeswat** [comment]
ya Berkeley Ecoengine External

**Comment by shoeswat** [comment]
[image: Inline image 1]

**Comment by danrademacher** [comment]
Great. So we've been including all issues here so we have a central place
to look. Issues are turned off for everyone on Ecoengine-compare.

-- 
Dan Rademacher
Project Director
dan@stamen.com
Mobile: 510.928.7799
Studio Phone: 415.558.1610

Stamen Design
2017 Mission Street, Suite 300
San Francisco, CA 94110

**Comment by shoeswat** [comment]
my bad, thx
