### ISSUE TITLE
Explore: Query page's Photo Gallery link is broken

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#159]
The API seems to work but the Photo Gallery link above it gives a 404 error; isnt the expected behaviour to show the thumbnail ribbon from Kai's earlier demos? (also broken in holos integrated instance)

**Comment by mkoo** [comment]
eg. query:
https://ecoengine.berkeley.edu/api/photos/?format=geojson&q=&bbox=-123.66294714695904,39.70547784907156,-123.60190899502979,39.762971163882675&page_size=80page=1

**Comment by danrademacher** [comment]
Not sure when that broke. Rather than trying to get that link to work at this late data, my recommendation would be to remove that "Photos" link from this line:
https://github.com/stamen/ecoengine/blob/bbba9de52f794675390fcf96dfd296b7fb97e397/templates/index.handlebars#L46

Is that an OK solution? The widget still works here: http://stamen.github.io/ecoengine/prototypes/photos/

**Comment by shoeswat** [comment]
I'll be working on fixing up stuff this weekend, I'll remove the link if I
can't get it to work

**Comment by shoeswat** [comment]
How is this thing supposed to work?

I tried
http://stamen.github.io/ecoengine/prototypes/photos/?q=lynx

All I get are flowers

**Comment by syntagmatic** [comment]
The URL should be: http://stamen.github.io/ecoengine/photos/?q=lynx

And it should display this file: https://github.com/stamen/ecoengine/blob/master/photos/index.html

The `gh-pages` branch got restructured by the build system and I guess photos was lost. Either move the latest photos to the `prototypes` directory, or put `photos` back into the top-level directory in the `gh-pages` branch.

**Comment by shoeswat** [comment]
@kai there are two photo directories, one in the prototypes and in the top
level. you know which one to keep?

**Comment by syntagmatic** [comment]
Keep the top level one in the `master` branch

**Comment by shoeswat** [comment]
I see photos in the top level:
https://github.com/berkeley-gif/ecoengine/tree/master/photos

But it doesn't seem to be found:
http://berkeley-gif.github.io/ecoengine/photos/

This seems to work same as stamen branch (with same bug, query doesn't work):
http://berkeley-gif.github.io/ecoengine/prototypes/photos

**Comment by syntagmatic** [comment]
Photos needs to be in the top level directory on the `gh-pages` pages branch for the link to appear.

https://github.com/berkeley-gif/ecoengine/tree/gh-pages

`/prototypes/photos` is an old version, it can be deleted.

**Comment by shoeswat** [comment]
ah so the photo in the root dir of the master branch goes in the root dir of ghpages?

**Comment by shoeswat** [comment]
i tried that, the query doesn't appear to go through
http://berkeley-gif.github.io/ecoengine/photos/?q=lynx

**Comment by syntagmatic** [comment]
Sorry, I miswrote the URL earlier. It needs a `#` symbol in front of the `?`. Everything after `#` gets appended to the Ecoengine query.

http://berkeley-gif.github.io/ecoengine/photos/#?q=lynx

**Comment by shoeswat** [comment]
ah cool thx

**Comment by syntagmatic** [comment]
![screen shot 2015-05-02 at 3 28 46 pm](https://cloud.githubusercontent.com/assets/156229/7443003/03d0a466-f0e0-11e4-92e1-699f967232e3.png)

**Comment by shoeswat** [comment]
thanks for you help. closing for now and opening a todo on holos. i just redirected the URL to github.io page. the photos app should be served from holos though.
