### ISSUE TITLE
Compare tool: color picker does not actually change the color (points do not update color)

### ISSUE THREAD

**Issue by shoeswat** [stamen/ecoengine#160]
They update, but you need to drag and drop to another field. Is there a way to do this on the fly?

**Comment by standardpixel** [comment]
@shoeswat May I ask what browser you are using and possibly the full link (including the stuff after "?state=") where you see this?

**Comment by shoeswat** [comment]
the state is the same no matter if its on github pages or in the website
right?

https://holos.berkeley.edu/compare/?state=N4IgtiBcDaoDYEsDOAXKIAOB7BA7FcAhgJ4CmATiADQhEBGpc6AKoeQgMYAWhABOwDcArkXZJqIIe3RcUKDEkgB6JaQ5ZSuAOZ5SAOgbkA1o1LE9pACZClhDAiVY6SCgMIoEWXEiUB%2BAGZY5GDuALxapFgAVkheAGQYhBEA%2BkgIAF6koQCsAAxxAI6hrOzcfIIibMgSCJboAIy5AMwAbAAsAEyWAOwAtP7%2B9f69bQCcLcOEpNn1vU3%2BLZbZlgAcK20rud0S6nBB6ADEHfUtLYQcIAC%2BALo0dZCgdFhCuJZsxL0ucGpokCASmgECHIXjAmhQn1MHF%2B%2FxoRDI5Eh32hMjkGGUSmASEuBkILhCCj0HDYKCwHEsuCJWDASkQWlkyVwWHojB8wHSl0xAA9OcBiDiMNorjRKH9tpcgAA%3D%3D#6/35.264/-127.551

You can try switching up the colors. They don't update on the map
immediately. However, they change if you drag and drop the box to another
section.

**Comment by standardpixel** [comment]
@shoeswat sorry for taking so long to get back to you. I found the line with the problem and have committed [a fix](https://github.com/stamen/ecoengine-compare/commit/a21e76ef46780d8cc2619e9628e666225610c4b6) to the master branch
