### ISSUE TITLE
"End Date" entry box should have hover text for ISO format

### ISSUE THREAD

**Issue by hconstable** [stamen/ecoengine#171]
The Begin Date box has hover text with ISO format, the end does not.

**Comment by syntagmatic** [comment]
Updated to display ISO format on hover. <img width="273" alt="screen shot 2016-01-20 at 4 56 24 am" src="https://cloud.githubusercontent.com/assets/156229/12449448/352c7834-bf32-11e5-9619-0c69b205d39d.png">

**Comment by syntagmatic** [comment]
Fixed in commit b2548bda0b0a52687f01864605a4af15f9f96a31
