### ISSUE TITLE
Get Query for Compare View yields long unwieldy link that is hard to copy

### ISSUE THREAD

**Issue by hconstable** [stamen/ecoengine#179]
This should show a shortened url that is easy to highlight and copy.

Clicking on "Go to Compare" would idealy automatically load this link in the Compare view. Otherwise, should say "copy link and click button below."

**Comment by syntagmatic** [comment]
Added word wrapping and dropped the font size so that long URLs stay in the viewable, selectable area.

<img width="463" alt="screen shot 2016-03-10 at 11 43 00 am" src="https://cloud.githubusercontent.com/assets/156229/13682078/2a17bf3a-e6b5-11e5-8da9-e3bf7490fff2.png">
