### ISSUE TITLE
legend for displayed raster - API

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#206]
For @bkg in API add grayscale (0-255) ramp which is required for color ramp customizations on the raster tool

**Comment by bkg** [comment]
@syntagmatic, turns out that a grayscale style is available by passing the `style` param, e.g. https://ecoengine.berkeley.edu/api/tiles/tasmin_yr_ens-avg_amon_rcp85-2099-01-01/4/3/6/?style=Greys. Let me know if this will suffice for the client side color ramps.

**Comment by syntagmatic** [comment]
Excellent, thanks @bkg!

Black corresponds to the max value and white to min, or vice versa?

**Comment by bkg** [comment]
That's right, but you can flip the ramp using `style=Greys_r` if you like.

**Comment by syntagmatic** [comment]
Thanks! I repaired this example: http://stamen.github.io/ecoengine/prototypes/tiles/colorscale.html

Legend coming soon
