### ISSUE TITLE
rstore filtering

### ISSUE THREAD

**Issue by syntagmatic** [stamen/ecoengine#211]
@bkg I think I tested this while we were meeting, but not now filtering in the rstore API doesn't seem to be working. Should this query filter to only rasters with the slug `pr_yr_ens-avg_amon_rcp45`?

https://ecoengine.berkeley.edu/api/rstore/?slug=pr_yr_ens-avg_amon_rcp45

**Comment by bkg** [comment]
Yeah, I don't see a slug filter for rstores. I think this can be achieved by accessing the rstores for a particular series, like https://ecoengine.berkeley.edu/api/series/pr_yr_ens-avg_amon_rcp45/rasters/.

**Comment by syntagmatic** [comment]
That works!
