### ISSUE TITLE
Reserve/Jepson page_size

### ISSUE THREAD

**Issue by syntagmatic** [stamen/ecoengine#212]
Doesn't look like the reserve and jepson regions APIs are honoring the `page_size` parameter:

https://ecoengine.berkeley.edu/api/layers/reserves/features/?page_size=100

Gives back 10 results @bkg

**Comment by bkg** [comment]
Thanks for letting me know, should be working now.

**Comment by syntagmatic** [comment]
Thanks! All reserves/regions showing up in Explore now.
