### ISSUE TITLE
No rasters for RCP 8.5

### ISSUE THREAD

**Issue by emilyhobson** [stamen/ecoengine#220]
One thing to note: there are no rasters to select for RCP 8.5.
Could be API issue? works with Modern and 4.5 scenarios

**Comment by syntagmatic** [comment]
Only the first two variables are missing 8.5, the last three all have rasters available.

![explore-raster-rcp85](https://cloud.githubusercontent.com/assets/156229/13688647/0b9d55a6-e6d8-11e5-8595-6a9c1f8dcd56.gif)

It looks like these are missing from the API, here's RCP 4.5 for the first series:

https://ecoengine.berkeley.edu/api/series/?slug=pr_yr_ens-avg_amon_rcp45

This URL should show rasters for RCP 8.5:

https://ecoengine.berkeley.edu/api/series/?slug=pr_yr_ens-avg_amon_rcp85

**Comment by emilyhobson** [comment]
@syntagmatic to make recommendation to Brian

**Comment by syntagmatic** [comment]
Discussed with this with @bkg in our code review
