### ISSUE TITLE
Display more than one search results in map

### ISSUE THREAD

**Issue by mkoo** [stamen/ecoengine#40]
(Adding as issue so we don't lose track of this functionality; see comment on blog and as per meeting 10/10)

Mapping results of different distinct search results. For example: search for ‘Ixodes pacificus’ and map results; while Ixodes results remain on map, search for ‘Neotoma’ and map results (now we can see where ticks and their favorite host reside!). One way to implement may be to send search results to a temp file via hashing that is mapped then run a fresh search. It is fine to have only one search be interactive in display table.

**Comment by danrademacher** [comment]
Done in compare UI
