### ISSUE TITLE
Remove Jepson checkbox

### ISSUE THREAD

**Issue by danrademacher** [stamen/ecoengine#86]
![image](https://cloud.githubusercontent.com/assets/1423200/5458476/491c3f5c-8507-11e4-96c6-dc9506841fe4.png)

**Comment by mkoo** [comment]
Can this be done in an hour or less? It's causing user confusion and needs to be removed. if not, I will put this on the our issue list to do.

**Comment by syntagmatic** [comment]
I updated the `gh-pages` branch to remove the checkbox. @evg or @postfalk will need to take a look for the Holos integration branch. Here's the change:

https://github.com/stamen/ecoengine/commit/c7bb5821362d65896dace9d454925dd5e701e642

Explore without Jepson checkbox:

http://stamen.github.io/ecoengine/explore

**Comment by mkoo** [comment]
looks good-- thanks for the quick response time; this will save a lot user
questions!

**Comment by standardpixel** [comment]
![screenshot 2015-04-21 14 48 05](https://cloud.githubusercontent.com/assets/15744/7263392/e82d9622-e835-11e4-993f-3bda98ce2375.png)
