### ISSUE TITLE
Create project structure that can be easily deployed within Mezzanine project

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#90]
This is currently a little bit a headache. I really want to be able to keep the application as one package working standalone as well as pull it as sub-module to the holos project. We would like to  serve it as Mezzanine templates and statics. 

I think something like 

```
ecoengine/
    ...
    explore/
        index.html
     static/
        css/ 
            stamen.css     # or some other name-spaced location
        js/
            stamen/
                config.js
                app.js
        vendor/
           d3.min.js
           leaflet.js
           etc.js
      ...
```

would work.

This somewhat deep structure reflects where stuff would go after running collectstatic in Mezzanine. In this case the standalone app would work the same way as the integrated one. A little bit complicates though. 

Another strategy would be to put everything into statics and evoke the app by attaching it to a ```<div name="something">``` which would give us some control over the surroundings.

Any thoughts on this. 

This would be of course part of the modularization, part of the next SOW.

**Comment by danrademacher** [comment]
Per @standardpixel and conversations with @postfalk, this should be accomplished now with the Bower structure in place
