### ISSUE TITLE
Discuss how to solve top navigation bar conflict

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#97]
@mkoo, @danrademacher, @syntagmatic, @shoeswat   

Currently both Stamen's app as well as holos page using top navigation bars that have to be somehow integrated. Before we get into the technical questions (Thanks @shoeswat for exploring.), we should decide on a couple of design questions.

Personally, I would move the search field and the time slider out of the top navigation bar in a somewhat more prominent position next to the map. The menu items *Reset*, *Advanced*, and *Query* could still be dynamically added to the holos top navbar.

@shoeswat suggested a somewhat different version that looks pretty good. He suggests to add the Stamen topnav bar fields to the actual holos top navigation bar. The problem, I see here is, that 1. the search field will be somewhat disconnected from the app (remember Charles' comment in which it was not obvious to him that the search field is the central entry point into a complex search), 2. the menu structure of the Holos site would be interrupted.

**Comment by danrademacher** [comment]
Solution is for Stamen to Make it look more like a toolbar and less like a top nav, which conflicts with Holos top nav.

**Comment by danrademacher** [comment]
Drop out the background color, make the white text black or dark gray to match rest of UI. Might mean some restyling on the brushable timeline

**Comment by standardpixel** [comment]
![screenshot 2015-02-26 10 49 41](https://cloud.githubusercontent.com/assets/15744/6401963/ec4a5b20-bdb8-11e4-83ed-487216ac0f46.png)

**Comment by postfalk** [comment]
Will pull this on, on Monday. Falk

On Thu, Feb 26, 2015 at 1:11 PM, Eric Gelinas <notifications@github.com>
wrote:

> Closed #97 <https://github.com/stamen/ecoengine/issues/97>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stamen/ecoengine/issues/97#event-242838251>.
>



-- 
Falk Schuetzenmeister, PhD
Web Application Developer
Geospatial Innovation Facility <http://gif.berkeley.edu/>

University of California Berkeley
111 Mulford Hall
94720 Berkeley, CA

schuetzenmeister@berkeley.edu
1-510-642-4897
