### ISSUE TITLE
Fix some css issues

### ISSUE THREAD

**Issue by postfalk** [stamen/ecoengine#98]
@syntagmatic and @postfalk  should figure out how the stylesheet could work as well on 

http://dev-holos.berkeley.edu/explore 
(use viewer/testuser to view the page).

There is currently an overlap between the map viewer and the result list. @syntagmatic Could we use bootstrap-3 scaffolding classes to fix this?

This issues is also connected to #97

**Comment by standardpixel** [comment]
![Uploading Screenshot 2015-02-26 10.49.41.png . . .]()
