### ISSUE TITLE
URL Character Encoding

### ISSUE THREAD

**Issue by syntagmatic** [stamen/ecoengine#99]
When using facet filters, encoded characters appear in the url like ```%3A``` and ```%22```. Example: http://studio.stamen.com/berkeley/show/ecoengine/explore/#&selected_facets=country_exact%3A%22Philippines%22&q=&min_date=1932-06-04&max_date=1949-03-23&page_size=100

These are functional urls, but they're not human-readable. The characters should be ```:``` and ```"```.

**Comment by danrademacher** [comment]
Closing this out
